model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"

  - model_name: text-embedding-bge
    litellm_params:
      model: openai/bge-small-en-v1.5
      api_base: "http://tei-embeddings:80/v1"

general_settings:
  master_key: "sk-master-key-change-me"
  database_url: "postgresql://litellm:litellm_pass@postgres-audit:5432/litellm_db"
